### ISSUE TITLE
CloudFlare Error 403: Forbidden when accessing api-analitica.suno.com.br

### ISSUE THREAD

**Issue by murillopaula** [Victorcorcos/bovespa-winner#15]
We get the following when attempting to run for example

```
# python3 graham.py

urllib.error.HTTPError: HTTP Error 403: Forbidden
```

This is because this URL `https://api-analitica.suno.com.br/api/Statement/GetStatementResultsReportByTicker?type=y&ticker=SOMA3&period=999` now requires some captcha.

**Comment by murillopaula** [comment]
@Victorcorcos quando vc criou o projeto tinha esse problema? tem que pagar pra não receber captchas da API da suno analytica?

**Comment by Victorcorcos** [comment]
Pois é 😞 

A Suno bloqueou o acesso... Coloquei mais detalhes aqui abaixo!
👇 
https://github.com/Victorcorcos/bovespa-winner/discussions/9
